"""Generate paper/FORMULA_CODE_MAP.md from the final paper's labels and check that every row resolves.

Labels are read from tools/paper_labels.json (extracted from the paper's LaTeX build by the authors; set QVDFE_AUX to an
.aux file to refresh it).
Every label must appear in tools/formula_code_map.json; every qvdfe function must import; every file must exist.
Exit status is nonzero if any label is unmapped or any row does not resolve.
"""
from pathlib import Path
import importlib
import json
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'src'))
import os
AUX = Path(os.environ['QVDFE_AUX']) if os.environ.get('QVDFE_AUX') else ROOT / 'build' / 'paper' / 'paper.aux'
LABELS = ROOT / 'tools' / 'paper_labels.json'
MAP = json.loads((ROOT / 'tools' / 'formula_code_map.json').read_text(encoding='utf-8'))
OUT = ROOT / 'FORMULA_CODE_MAP.md'

if AUX.exists():
    pat = re.compile(r'\\newlabel\{([^}@]+)\}\{\{([^}]*)\}')
    labels = []
    for m in pat.finditer(AUX.read_text(encoding='utf-8', errors='replace')):
        if m.group(1) not in [x[0] for x in labels]:
            labels.append([m.group(1), m.group(2)])
    LABELS.write_text(json.dumps(labels, indent=0), encoding='utf-8')
labels = json.loads(LABELS.read_text(encoding='utf-8'))


def resolve(item):
    if not item:
        return True
    if item.startswith('qvdfe.'):
        parts = item.split('.')
        try:
            obj = importlib.import_module('qvdfe')
            for p in parts[1:]:
                obj = getattr(obj, p) if hasattr(obj, p) else importlib.import_module('.'.join(parts[:parts.index(p) + 1]))
            return True
        except Exception:  # noqa: BLE001
            return False
    p = ROOT / item
    return p.exists() or (item.startswith('data/frozen/') and (ROOT / 'data' / item[len('data/frozen/'):]).exists())


KIND = {'eq': 'Eq.', 'fig': 'Fig.', 'tab': 'Table', 'sec': 'Section', 'app': 'Appendix'}
rows, unmapped, unresolved = [], [], []
for lab, num in labels:
    kind = KIND.get(lab.split(':')[0], lab.split(':')[0])
    if lab not in MAP:
        unmapped.append(lab)
        continue
    code, learn, inp, note = MAP[lab]
    for it in (code, learn, inp):
        if not resolve(it):
            unresolved.append((lab, it))
    fmt = lambda s: f'`{s}`' if s else ''
    rows.append(f'| {kind} {num} | `{lab}` | {fmt(code)} | {fmt(learn)} | {fmt(inp)} | {note} |')
extra = [k for k in MAP if not k.startswith('_') and k not in [x[0] for x in labels]]

md = ['# Formula–code map', '',
      'Generated by `tools/make_formula_code_map.py` from the labels of the final paper. Each row links a paper item to its core function in `src/qvdfe`, or to the reproduction entry that redraws it. Each row also gives a tutorial or example that uses it and the input file. "Frozen output; producing code not included" means the result is in `data/frozen` but the code that produced it from the original data is not part of this repository.', '',
      '| Paper item | Label | Code | Tutorial or example | Input | Note |', '| --- | --- | --- | --- | --- | --- |'] + rows
OUT.write_text('\n'.join(md) + '\n', encoding='utf-8', newline='\n')
print(f'{len(rows)} rows written to {OUT.relative_to(ROOT)}; unmapped labels: {unmapped}; unresolved: {unresolved}; map entries not in paper: {extra}')
sys.exit(1 if unmapped or unresolved else 0)
